name: Py-Flask
env:
  EB_PACKAGE_S3_BUSKEET_NAME: "flask-app-packeges"
  EB_APPLICATION_NAME: "Py-Flask"
  EB_ENVIRONMENT_NAME: "Py-Flask"
  DEPLOY_PACKAGES_NAME: "flask_app${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"
  
on:
  push:
    branches:
      -master
      
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1

    - name: Create ZIP deployment packeges
      run: zip -r ${{ env.DEPLOY_PACKAGES_NAME }} ./ -x *.git*
